alter table public.master_medicines
  add column if not exists category text not null default 'Other';

create index if not exists master_medicines_category_idx
  on public.master_medicines(active, category, lower(product_name));

update public.master_medicines set category = case
  when generic_name in ('Paracetamol', 'Diclofenac sodium', 'Ibuprofen') then 'Pain & Fever'
  when generic_name in ('Amoxicillin', 'Metronidazole', 'Ciprofloxacin', 'Azithromycin', 'Sulfamethoxazole/Trimethoprim') then 'Antibiotics & Antimicrobials'
  when generic_name in ('Cetirizine', 'Loratadine', 'Salbutamol') then 'Allergy & Respiratory'
  when generic_name in ('Omeprazole', 'Oral rehydration salts', 'Zinc sulfate') then 'Digestive Health'
  when generic_name in ('Amlodipine', 'Metformin') then 'Chronic Care'
  when generic_name in ('Hydrocortisone', 'Clotrimazole') then 'Skin Care'
  else category end
where category = 'Other';

insert into public.master_medicines
  (product_name, generic_name, strength, dosage_form, base_unit, pack_type, units_per_pack, default_selling_mode, category)
values
  ('Paracetamol 250 mg/5 mL Oral Suspension', 'Paracetamol', '250 mg/5 mL', 'Oral suspension', 'bottle', 'bottle', 1, 'PACK', 'Pain & Fever'),
  ('Paracetamol 100 mg Suppositories', 'Paracetamol', '100 mg', 'Suppository', 'suppository', 'box', 10, 'BOTH', 'Pain & Fever'),
  ('Paracetamol 1 g Tablets', 'Paracetamol', '1 g', 'Tablet', 'tablet', 'strip', 10, 'BOTH', 'Pain & Fever'),
  ('Ibuprofen 200 mg Tablets', 'Ibuprofen', '200 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Pain & Fever'),
  ('Ibuprofen 100 mg/5 mL Suspension', 'Ibuprofen', '100 mg/5 mL', 'Oral suspension', 'bottle', 'bottle', 1, 'PACK', 'Pain & Fever'),
  ('Diclofenac 100 mg Sustained Release Tablets', 'Diclofenac sodium', '100 mg', 'Sustained-release tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Pain & Fever'),
  ('Diclofenac 75 mg/3 mL Injection', 'Diclofenac sodium', '75 mg/3 mL', 'Injection', 'ampoule', 'box', 10, 'BOTH', 'Pain & Fever'),
  ('Diclofenac 1% Gel', 'Diclofenac sodium', '1%', 'Gel', 'tube', 'tube', 1, 'PACK', 'Pain & Fever'),
  ('Aspirin 75 mg Tablets', 'Acetylsalicylic acid', '75 mg', 'Tablet', 'tablet', 'blister pack', 28, 'BOTH', 'Pain & Fever'),
  ('Aspirin 300 mg Tablets', 'Acetylsalicylic acid', '300 mg', 'Tablet', 'tablet', 'strip', 10, 'BOTH', 'Pain & Fever'),
  ('Naproxen 500 mg Tablets', 'Naproxen', '500 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Pain & Fever'),
  ('Meloxicam 7.5 mg Tablets', 'Meloxicam', '7.5 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Pain & Fever'),
  ('Celecoxib 200 mg Capsules', 'Celecoxib', '200 mg', 'Capsule', 'capsule', 'blister pack', 10, 'BOTH', 'Pain & Fever'),
  ('Tramadol 50 mg Capsules', 'Tramadol', '50 mg', 'Capsule', 'capsule', 'blister pack', 10, 'BOTH', 'Pain & Fever'),
  ('Menthol Methyl Salicylate Rub', 'Menthol/Methyl salicylate', '', 'Topical rub', 'jar', 'jar', 1, 'PACK', 'Pain & Fever'),

  ('Amoxicillin 250 mg Capsules', 'Amoxicillin', '250 mg', 'Capsule', 'capsule', 'blister pack', 10, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Amoxicillin Clavulanate 625 mg Tablets', 'Amoxicillin/Clavulanic acid', '500 mg/125 mg', 'Tablet', 'tablet', 'blister pack', 14, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Amoxicillin Clavulanate 457 mg/5 mL Suspension', 'Amoxicillin/Clavulanic acid', '457 mg/5 mL', 'Oral suspension', 'bottle', 'bottle', 1, 'PACK', 'Antibiotics & Antimicrobials'),
  ('Flucloxacillin 500 mg Capsules', 'Flucloxacillin', '500 mg', 'Capsule', 'capsule', 'blister pack', 10, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Ampicillin 500 mg Capsules', 'Ampicillin', '500 mg', 'Capsule', 'capsule', 'blister pack', 10, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Cefalexin 500 mg Capsules', 'Cefalexin', '500 mg', 'Capsule', 'capsule', 'blister pack', 10, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Cefuroxime 500 mg Tablets', 'Cefuroxime', '500 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Cefixime 200 mg Tablets', 'Cefixime', '200 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Ceftriaxone 1 g Injection', 'Ceftriaxone', '1 g', 'Powder for injection', 'vial', 'box', 10, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Doxycycline 100 mg Capsules', 'Doxycycline', '100 mg', 'Capsule', 'capsule', 'blister pack', 10, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Erythromycin 500 mg Tablets', 'Erythromycin', '500 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Clarithromycin 500 mg Tablets', 'Clarithromycin', '500 mg', 'Tablet', 'tablet', 'blister pack', 14, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Levofloxacin 500 mg Tablets', 'Levofloxacin', '500 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Norfloxacin 400 mg Tablets', 'Norfloxacin', '400 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Tinidazole 500 mg Tablets', 'Tinidazole', '500 mg', 'Tablet', 'tablet', 'blister pack', 4, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Co-trimoxazole 960 mg Tablets', 'Sulfamethoxazole/Trimethoprim', '800 mg/160 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Co-trimoxazole 240 mg/5 mL Suspension', 'Sulfamethoxazole/Trimethoprim', '240 mg/5 mL', 'Oral suspension', 'bottle', 'bottle', 1, 'PACK', 'Antibiotics & Antimicrobials'),
  ('Nitrofurantoin 100 mg Tablets', 'Nitrofurantoin', '100 mg', 'Tablet', 'tablet', 'blister pack', 14, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Benzylpenicillin 5 MU Injection', 'Benzylpenicillin', '5 MU', 'Powder for injection', 'vial', 'box', 10, 'BOTH', 'Antibiotics & Antimicrobials'),
  ('Gentamicin 80 mg/2 mL Injection', 'Gentamicin', '80 mg/2 mL', 'Injection', 'ampoule', 'box', 10, 'BOTH', 'Antibiotics & Antimicrobials'),

  ('Artemether Lumefantrine 20/120 mg Tablets 6s', 'Artemether/Lumefantrine', '20 mg/120 mg', 'Tablet', 'tablet', 'blister pack', 6, 'PACK', 'Malaria & Parasites'),
  ('Artemether Lumefantrine 20/120 mg Tablets 12s', 'Artemether/Lumefantrine', '20 mg/120 mg', 'Tablet', 'tablet', 'blister pack', 12, 'PACK', 'Malaria & Parasites'),
  ('Artemether Lumefantrine 20/120 mg Tablets 18s', 'Artemether/Lumefantrine', '20 mg/120 mg', 'Tablet', 'tablet', 'blister pack', 18, 'PACK', 'Malaria & Parasites'),
  ('Artemether Lumefantrine 20/120 mg Tablets 24s', 'Artemether/Lumefantrine', '20 mg/120 mg', 'Tablet', 'tablet', 'blister pack', 24, 'PACK', 'Malaria & Parasites'),
  ('Artesunate 60 mg Injection', 'Artesunate', '60 mg', 'Powder for injection', 'vial', 'pack', 1, 'PACK', 'Malaria & Parasites'),
  ('Quinine 300 mg Tablets', 'Quinine sulfate', '300 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Malaria & Parasites'),
  ('Quinine 600 mg/2 mL Injection', 'Quinine dihydrochloride', '600 mg/2 mL', 'Injection', 'ampoule', 'box', 10, 'BOTH', 'Malaria & Parasites'),
  ('Albendazole 400 mg Tablets', 'Albendazole', '400 mg', 'Tablet', 'tablet', 'blister pack', 1, 'PACK', 'Malaria & Parasites'),
  ('Albendazole 200 mg/5 mL Suspension', 'Albendazole', '200 mg/5 mL', 'Oral suspension', 'bottle', 'bottle', 1, 'PACK', 'Malaria & Parasites'),
  ('Mebendazole 100 mg Tablets', 'Mebendazole', '100 mg', 'Tablet', 'tablet', 'blister pack', 6, 'PACK', 'Malaria & Parasites'),
  ('Praziquantel 600 mg Tablets', 'Praziquantel', '600 mg', 'Tablet', 'tablet', 'bottle', 100, 'BOTH', 'Malaria & Parasites'),
  ('Ivermectin 6 mg Tablets', 'Ivermectin', '6 mg', 'Tablet', 'tablet', 'blister pack', 4, 'BOTH', 'Malaria & Parasites'),

  ('Chlorpheniramine 4 mg Tablets', 'Chlorpheniramine', '4 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Allergy & Respiratory'),
  ('Chlorpheniramine 2 mg/5 mL Syrup', 'Chlorpheniramine', '2 mg/5 mL', 'Syrup', 'bottle', 'bottle', 1, 'PACK', 'Allergy & Respiratory'),
  ('Cetirizine 5 mg/5 mL Syrup', 'Cetirizine', '5 mg/5 mL', 'Syrup', 'bottle', 'bottle', 1, 'PACK', 'Allergy & Respiratory'),
  ('Promethazine 25 mg Tablets', 'Promethazine', '25 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Allergy & Respiratory'),
  ('Promethazine 5 mg/5 mL Syrup', 'Promethazine', '5 mg/5 mL', 'Syrup', 'bottle', 'bottle', 1, 'PACK', 'Allergy & Respiratory'),
  ('Salbutamol 4 mg Tablets', 'Salbutamol', '4 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Allergy & Respiratory'),
  ('Salbutamol 2 mg/5 mL Syrup', 'Salbutamol', '2 mg/5 mL', 'Syrup', 'bottle', 'bottle', 1, 'PACK', 'Allergy & Respiratory'),
  ('Salbutamol 2.5 mg/2.5 mL Nebules', 'Salbutamol', '2.5 mg/2.5 mL', 'Nebuliser solution', 'nebule', 'box', 20, 'BOTH', 'Allergy & Respiratory'),
  ('Beclometasone 50 mcg Inhaler', 'Beclometasone', '50 mcg/dose', 'Inhaler', 'inhaler', 'inhaler', 1, 'PACK', 'Allergy & Respiratory'),
  ('Budesonide Formoterol 160/4.5 mcg Inhaler', 'Budesonide/Formoterol', '160 mcg/4.5 mcg', 'Inhaler', 'inhaler', 'inhaler', 1, 'PACK', 'Allergy & Respiratory'),
  ('Montelukast 10 mg Tablets', 'Montelukast', '10 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Allergy & Respiratory'),
  ('Dextromethorphan Cough Syrup', 'Dextromethorphan', '15 mg/5 mL', 'Syrup', 'bottle', 'bottle', 1, 'PACK', 'Allergy & Respiratory'),
  ('Bromhexine 4 mg/5 mL Syrup', 'Bromhexine', '4 mg/5 mL', 'Syrup', 'bottle', 'bottle', 1, 'PACK', 'Allergy & Respiratory'),
  ('Saline Nasal Drops 10 mL', 'Sodium chloride', '0.9%', 'Nasal drops', 'bottle', 'bottle', 1, 'PACK', 'Allergy & Respiratory'),

  ('Omeprazole 40 mg Capsules', 'Omeprazole', '40 mg', 'Capsule', 'capsule', 'blister pack', 14, 'BOTH', 'Digestive Health'),
  ('Pantoprazole 40 mg Tablets', 'Pantoprazole', '40 mg', 'Tablet', 'tablet', 'blister pack', 14, 'BOTH', 'Digestive Health'),
  ('Esomeprazole 20 mg Capsules', 'Esomeprazole', '20 mg', 'Capsule', 'capsule', 'blister pack', 14, 'BOTH', 'Digestive Health'),
  ('Famotidine 20 mg Tablets', 'Famotidine', '20 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Digestive Health'),
  ('Magnesium Trisilicate Mixture', 'Magnesium trisilicate compound', '', 'Oral suspension', 'bottle', 'bottle', 1, 'PACK', 'Digestive Health'),
  ('Aluminium Hydroxide Magnesium Hydroxide Suspension', 'Aluminium hydroxide/Magnesium hydroxide', '', 'Oral suspension', 'bottle', 'bottle', 1, 'PACK', 'Digestive Health'),
  ('Hyoscine Butylbromide 10 mg Tablets', 'Hyoscine butylbromide', '10 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Digestive Health'),
  ('Loperamide 2 mg Capsules', 'Loperamide', '2 mg', 'Capsule', 'capsule', 'blister pack', 10, 'BOTH', 'Digestive Health'),
  ('Bisacodyl 5 mg Tablets', 'Bisacodyl', '5 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Digestive Health'),
  ('Lactulose Oral Solution', 'Lactulose', '3.35 g/5 mL', 'Oral solution', 'bottle', 'bottle', 1, 'PACK', 'Digestive Health'),
  ('Senna 7.5 mg Tablets', 'Sennosides', '7.5 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Digestive Health'),
  ('Metoclopramide 10 mg Tablets', 'Metoclopramide', '10 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Digestive Health'),
  ('Ondansetron 4 mg Tablets', 'Ondansetron', '4 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Digestive Health'),
  ('Domperidone 10 mg Tablets', 'Domperidone', '10 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Digestive Health'),

  ('Amlodipine 10 mg Tablets', 'Amlodipine', '10 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Chronic Care'),
  ('Nifedipine Retard 20 mg Tablets', 'Nifedipine', '20 mg', 'Sustained-release tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Chronic Care'),
  ('Enalapril 5 mg Tablets', 'Enalapril', '5 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Chronic Care'),
  ('Enalapril 10 mg Tablets', 'Enalapril', '10 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Chronic Care'),
  ('Losartan 50 mg Tablets', 'Losartan', '50 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Chronic Care'),
  ('Hydrochlorothiazide 25 mg Tablets', 'Hydrochlorothiazide', '25 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Chronic Care'),
  ('Furosemide 40 mg Tablets', 'Furosemide', '40 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Chronic Care'),
  ('Spironolactone 25 mg Tablets', 'Spironolactone', '25 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Chronic Care'),
  ('Atenolol 50 mg Tablets', 'Atenolol', '50 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Chronic Care'),
  ('Propranolol 40 mg Tablets', 'Propranolol', '40 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Chronic Care'),
  ('Atorvastatin 20 mg Tablets', 'Atorvastatin', '20 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Chronic Care'),
  ('Simvastatin 20 mg Tablets', 'Simvastatin', '20 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Chronic Care'),
  ('Clopidogrel 75 mg Tablets', 'Clopidogrel', '75 mg', 'Tablet', 'tablet', 'blister pack', 28, 'BOTH', 'Chronic Care'),
  ('Metformin 850 mg Tablets', 'Metformin', '850 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Chronic Care'),
  ('Glibenclamide 5 mg Tablets', 'Glibenclamide', '5 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Chronic Care'),
  ('Gliclazide 80 mg Tablets', 'Gliclazide', '80 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Chronic Care'),
  ('Human Insulin Soluble 100 IU/mL', 'Human insulin soluble', '100 IU/mL', 'Injection', 'vial', 'vial', 1, 'PACK', 'Chronic Care'),
  ('Isophane Insulin 100 IU/mL', 'Isophane insulin', '100 IU/mL', 'Injection', 'vial', 'vial', 1, 'PACK', 'Chronic Care'),

  ('Hydrocortisone 1% Ointment', 'Hydrocortisone', '1%', 'Ointment', 'tube', 'tube', 1, 'PACK', 'Skin Care'),
  ('Clotrimazole 1% Solution', 'Clotrimazole', '1%', 'Topical solution', 'bottle', 'bottle', 1, 'PACK', 'Skin Care'),
  ('Ketoconazole 2% Cream', 'Ketoconazole', '2%', 'Cream', 'tube', 'tube', 1, 'PACK', 'Skin Care'),
  ('Ketoconazole 2% Shampoo', 'Ketoconazole', '2%', 'Shampoo', 'bottle', 'bottle', 1, 'PACK', 'Skin Care'),
  ('Miconazole 2% Cream', 'Miconazole', '2%', 'Cream', 'tube', 'tube', 1, 'PACK', 'Skin Care'),
  ('Betamethasone 0.1% Cream', 'Betamethasone valerate', '0.1%', 'Cream', 'tube', 'tube', 1, 'PACK', 'Skin Care'),
  ('Calamine Lotion', 'Calamine', '', 'Lotion', 'bottle', 'bottle', 1, 'PACK', 'Skin Care'),
  ('Benzyl Benzoate 25% Lotion', 'Benzyl benzoate', '25%', 'Lotion', 'bottle', 'bottle', 1, 'PACK', 'Skin Care'),
  ('Permethrin 5% Cream', 'Permethrin', '5%', 'Cream', 'tube', 'tube', 1, 'PACK', 'Skin Care'),
  ('Povidone Iodine 10% Solution', 'Povidone iodine', '10%', 'Topical solution', 'bottle', 'bottle', 1, 'PACK', 'Skin Care'),
  ('Silver Sulfadiazine 1% Cream', 'Silver sulfadiazine', '1%', 'Cream', 'tube', 'tube', 1, 'PACK', 'Skin Care'),
  ('Fusidic Acid 2% Cream', 'Fusidic acid', '2%', 'Cream', 'tube', 'tube', 1, 'PACK', 'Skin Care'),

  ('Chloramphenicol 0.5% Eye Drops', 'Chloramphenicol', '0.5%', 'Eye drops', 'bottle', 'bottle', 1, 'PACK', 'Eye & Ear Care'),
  ('Ciprofloxacin 0.3% Eye Drops', 'Ciprofloxacin', '0.3%', 'Eye drops', 'bottle', 'bottle', 1, 'PACK', 'Eye & Ear Care'),
  ('Gentamicin 0.3% Eye Drops', 'Gentamicin', '0.3%', 'Eye drops', 'bottle', 'bottle', 1, 'PACK', 'Eye & Ear Care'),
  ('Tetracycline 1% Eye Ointment', 'Tetracycline', '1%', 'Eye ointment', 'tube', 'tube', 1, 'PACK', 'Eye & Ear Care'),
  ('Artificial Tears Eye Drops', 'Hypromellose', '0.3%', 'Eye drops', 'bottle', 'bottle', 1, 'PACK', 'Eye & Ear Care'),
  ('Timolol 0.5% Eye Drops', 'Timolol', '0.5%', 'Eye drops', 'bottle', 'bottle', 1, 'PACK', 'Eye & Ear Care'),
  ('Dexamethasone 0.1% Eye Drops', 'Dexamethasone', '0.1%', 'Eye drops', 'bottle', 'bottle', 1, 'PACK', 'Eye & Ear Care'),
  ('Ciprofloxacin 0.3% Ear Drops', 'Ciprofloxacin', '0.3%', 'Ear drops', 'bottle', 'bottle', 1, 'PACK', 'Eye & Ear Care'),
  ('Wax Solvent Ear Drops', 'Choline salicylate/Glycerol', '', 'Ear drops', 'bottle', 'bottle', 1, 'PACK', 'Eye & Ear Care'),

  ('Ferrous Sulfate 200 mg Tablets', 'Ferrous sulfate', '200 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Vitamins & Nutrition'),
  ('Folic Acid 5 mg Tablets', 'Folic acid', '5 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Vitamins & Nutrition'),
  ('Ferrous Sulfate Folic Acid Tablets', 'Ferrous sulfate/Folic acid', '', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Vitamins & Nutrition'),
  ('Vitamin C 500 mg Tablets', 'Ascorbic acid', '500 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Vitamins & Nutrition'),
  ('Vitamin B Complex Tablets', 'Vitamin B complex', '', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Vitamins & Nutrition'),
  ('Multivitamin Tablets', 'Multivitamins', '', 'Tablet', 'tablet', 'bottle', 30, 'BOTH', 'Vitamins & Nutrition'),
  ('Multivitamin Syrup', 'Multivitamins', '', 'Syrup', 'bottle', 'bottle', 1, 'PACK', 'Vitamins & Nutrition'),
  ('Calcium Vitamin D Tablets', 'Calcium carbonate/Cholecalciferol', '', 'Tablet', 'tablet', 'bottle', 30, 'BOTH', 'Vitamins & Nutrition'),
  ('Vitamin D3 1000 IU Tablets', 'Cholecalciferol', '1000 IU', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Vitamins & Nutrition'),
  ('Zinc 20 mg Tablets', 'Zinc sulfate', '20 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Vitamins & Nutrition'),

  ('Ethinylestradiol Levonorgestrel Tablets', 'Ethinylestradiol/Levonorgestrel', '30 mcg/150 mcg', 'Tablet', 'tablet', 'calendar pack', 28, 'PACK', 'Women''s Health'),
  ('Levonorgestrel 1.5 mg Emergency Contraceptive', 'Levonorgestrel', '1.5 mg', 'Tablet', 'tablet', 'pack', 1, 'PACK', 'Women''s Health'),
  ('Medroxyprogesterone 150 mg/mL Injection', 'Medroxyprogesterone acetate', '150 mg/mL', 'Injection', 'vial', 'vial', 1, 'PACK', 'Women''s Health'),
  ('Clotrimazole 500 mg Vaginal Tablet', 'Clotrimazole', '500 mg', 'Vaginal tablet', 'tablet', 'pack', 1, 'PACK', 'Women''s Health'),
  ('Clotrimazole 100 mg Vaginal Tablets', 'Clotrimazole', '100 mg', 'Vaginal tablet', 'tablet', 'pack', 6, 'PACK', 'Women''s Health'),
  ('Metronidazole 500 mg Vaginal Tablets', 'Metronidazole', '500 mg', 'Vaginal tablet', 'tablet', 'pack', 10, 'PACK', 'Women''s Health'),
  ('Pregnancy Test Strip', 'Human chorionic gonadotropin test', '', 'Diagnostic test', 'test', 'box', 50, 'BOTH', 'Women''s Health'),

  ('Prednisolone 5 mg Tablets', 'Prednisolone', '5 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Other Medicines'),
  ('Dexamethasone 4 mg Tablets', 'Dexamethasone', '4 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Other Medicines'),
  ('Dexamethasone 4 mg/mL Injection', 'Dexamethasone', '4 mg/mL', 'Injection', 'ampoule', 'box', 10, 'BOTH', 'Other Medicines'),
  ('Diazepam 5 mg Tablets', 'Diazepam', '5 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Other Medicines'),
  ('Carbamazepine 200 mg Tablets', 'Carbamazepine', '200 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Other Medicines'),
  ('Amitriptyline 25 mg Tablets', 'Amitriptyline', '25 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Other Medicines'),
  ('Fluconazole 150 mg Capsules', 'Fluconazole', '150 mg', 'Capsule', 'capsule', 'blister pack', 1, 'PACK', 'Other Medicines'),
  ('Acyclovir 400 mg Tablets', 'Acyclovir', '400 mg', 'Tablet', 'tablet', 'blister pack', 10, 'BOTH', 'Other Medicines'),
  ('Nystatin 100000 IU/mL Oral Suspension', 'Nystatin', '100000 IU/mL', 'Oral suspension', 'bottle', 'bottle', 1, 'PACK', 'Other Medicines'),
  ('Levothyroxine 50 mcg Tablets', 'Levothyroxine', '50 mcg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Other Medicines'),
  ('Allopurinol 100 mg Tablets', 'Allopurinol', '100 mg', 'Tablet', 'tablet', 'blister pack', 30, 'BOTH', 'Other Medicines'),

  ('Disposable Syringe 2 mL', 'Disposable syringe', '2 mL', 'Medical supply', 'syringe', 'box', 100, 'BOTH', 'Medical Supplies'),
  ('Disposable Syringe 5 mL', 'Disposable syringe', '5 mL', 'Medical supply', 'syringe', 'box', 100, 'BOTH', 'Medical Supplies'),
  ('Disposable Syringe 10 mL', 'Disposable syringe', '10 mL', 'Medical supply', 'syringe', 'box', 100, 'BOTH', 'Medical Supplies'),
  ('Insulin Syringe 1 mL', 'Insulin syringe', '1 mL', 'Medical supply', 'syringe', 'box', 100, 'BOTH', 'Medical Supplies'),
  ('Examination Gloves Medium', 'Latex examination gloves', 'Medium', 'Medical supply', 'pair', 'box', 50, 'BOTH', 'Medical Supplies'),
  ('Surgical Gloves Size 7.5', 'Sterile surgical gloves', '7.5', 'Medical supply', 'pair', 'box', 50, 'BOTH', 'Medical Supplies'),
  ('Cotton Wool 100 g', 'Absorbent cotton wool', '100 g', 'Medical supply', 'roll', 'pack', 1, 'PACK', 'Medical Supplies'),
  ('Gauze Swabs 10 cm x 10 cm', 'Gauze swabs', '10 cm x 10 cm', 'Medical supply', 'swab', 'pack', 100, 'BOTH', 'Medical Supplies'),
  ('Crepe Bandage 10 cm', 'Elastic crepe bandage', '10 cm', 'Medical supply', 'roll', 'pack', 1, 'PACK', 'Medical Supplies'),
  ('Adhesive Plaster Roll', 'Zinc oxide adhesive plaster', '', 'Medical supply', 'roll', 'pack', 1, 'PACK', 'Medical Supplies'),
  ('Digital Thermometer', 'Digital thermometer', '', 'Medical device', 'device', 'box', 1, 'PACK', 'Medical Supplies'),
  ('Surgical Face Masks', 'Surgical face mask', '', 'Medical supply', 'mask', 'box', 50, 'BOTH', 'Medical Supplies'),
  ('Hand Sanitizer 500 mL', 'Alcohol hand rub', '70%', 'Hand rub', 'bottle', 'bottle', 1, 'PACK', 'Medical Supplies'),
  ('Blood Glucose Test Strips', 'Blood glucose test strips', '', 'Diagnostic supply', 'strip', 'box', 50, 'BOTH', 'Medical Supplies'),
  ('Urine Test Strips 10 Parameter', 'Urinalysis reagent strips', '10 parameter', 'Diagnostic supply', 'strip', 'bottle', 100, 'BOTH', 'Medical Supplies')
on conflict do nothing;
